# Generated by Django 5.2.3 on 2025-06-11 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen_url', models.URLField(default='https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/7b/44/2a/carbon-2.jpg?w=900&h=500&s=1', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Repartidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=20)),
                ('precio_medio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('media_valoracion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('imagen_url', models.URLField(default='https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/7b/44/2a/carbon-2.jpg?w=900&h=500&s=1', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('tarjeta', models.CharField(max_length=20)),
                ('cad_tarjeta', models.CharField(max_length=5)),
                ('cvv_tarjeta', models.CharField(max_length=3)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.restaurantes'),
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('numero_personas', models.IntegerField()),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.restaurantes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_entrega', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En preparación', 'En preparación'), ('En camino', 'En camino'), ('Entregado', 'Entregado')], max_length=20)),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.repartidores')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.restaurantes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Opiniones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('comentario', models.TextField()),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.restaurantes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.productos')),
            ],
            options={
                'unique_together': {('pedido', 'producto')},
            },
        ),
    ]
